package bookstore;

public class BookInventory {
        public static Book[] findAll() {
            return new Book[]{
                    new Book("Citizen Kane", 6, "bleH"),
                    new Book("Casablanca", 6,"bleh"),
                    new Book("The Godfather",4, "drama"),
                    new Book("Gone With The Wind",4, "drama"),
                    new Book("Lawrence Of Arabia",4, "drama"),
                    new Book("The Wizard Of Oz",4, "musical"),
                    new Book("The Graduate", 4,"drama"),
                    new Book("On The Waterfront",4, "drama"),
                    new Book("Schindler's List",4, "drama"),
                    new Book("Singin' In The Rain", 4,"musical"),
                    new Book("It's A Wonderful Life",4, "drama"),
                    new Book("Sunset Boulevard", 4,"drama"),
                    new Book("The Bridge On The River Kwai",4, "drama"),
                    new Book("Some Like It Hot", 4,"drama"),
                    new Book("Star Wars",4, "scifi"),
                    new Book("All About Eve",4, "drama"),
                    new Book("The African Queen",4, "drama"),
                    new Book("Psycho", 6,"horror"),
                    new Book("Chinatown", 6,"drama"),
                    new Book("One Flew Over The Cuckoo's Nest",5, "drama"),
                    new Book("The Grapes Of Wrath",5, "drama"),
                    new Book("2001: A Space Odyssey",5, "scifi"),
                    new Book("The Maltese Falcon",5, "drama"),
                    new Book("Raging Bull",5, "drama"),
                    new Book("E.T. The extra-terrestrial",5, "scifi"),
                    new Book("Dr. Strangelove",5, "drama"),
                    new Book("Bonnie And Clyde",5, "drama"),
                    new Book("Apocalypse Now",5, "drama"),
                    new Book("Mr. Smith Goes to Washington",5, "drama"),
                    new Book("The Treasure Of The Sierra Madre",5, "drama"),
                    new Book("Annie Hall",5, "comedy"),
                    new Book("The Godfather Part II",5, "yolo"),
                    new Book("High Noon",5, "drama"),
                    new Book("To Kill A Mockingbird",5, "drama"),
                    new Book("It Happened One Night",5, "drama"),
                    new Book("Midnight Cowboy",5, "drama"),
                    new Book("The Best Years Of Our Lives",5, "drama"),
                    new Book("Double Indemnity",5, "drama"),
                    new Book("Doctor Zhivago",5, "drama"),
//                    new Book("North By Northwest",5, "drama"),
//                    new Movie("West Side Story", "musical"),
//                    new Movie("Rear Window", "drama"),
//                    new Movie("King Kong", "horror"),
//                    new Movie("The Birth Of A Nation", "drama"),
//                    new Movie("A Streetcar Named Desire", "drama"),
//                    new Movie("A Clockwork Orange", "scifi"),
//                    new Movie("Taxi Driver", "drama"),
//                    new Movie("Jaws", "horror"),
//                    new Movie("Snow White And The Seven Dwarfs", "animated"),
//                    new Movie("Butch Cassidy And The Sundance Kid", "drama"),
//                    new Movie("The Philadelphia Story", "drama"),
//                    new Movie("From Here To Eternity", "drama"),
//                    new Movie("Amadeus", "drama"),
//                    new Movie("All Quiet On The Western Front", "drama"),
//                    new Movie("The Sound Of Music", "musical"),
//                    new Movie("M*A*S*H", "comedy"),
//                    new Movie("The Third Man", "drama"),
//                    new Movie("Fantasia", "animated"),
//                    new Movie("Rebel Without A Cause", "drama"),
//                    new Movie("Raiders Of The Lost Ark", "drama"),
//                    new Movie("Vertigo", "drama"),
//                    new Movie("Tootsie", "comedy"),
//                    new Movie("Stagecoach", "drama"),
//                    new Movie("Close Encounters Of The Third Kind", "scifi"),
//                    new Movie("The Silence Of The Lambs", "horror"),
//                    new Movie("Network", "drama"),
//                    new Movie("The Manchurian Candidate", "drama"),
//                    new Movie("An American In Paris", "drama"),
//                    new Movie("Shane", "drama"),
//                    new Movie("The French Connection", "drama"),
//                    new Movie("Forrest Gump", "drama"),
//                    new Movie("Ben-Hur", "drama"),
//                    new Movie("Wuthering Heights", "drama"),
//                    new Movie("The Gold Rush", "drama"),
//                    new Movie("Dances With Wolves", "drama"),
//                    new Movie("City Lights", "drama"),
//                    new Movie("American Graffiti", "drama"),
//                    new Movie("Rocky", "drama"),
//                    new Movie("The Deer Hunter", "drama"),
//                    new Movie("The Wild Bunch", "drama"),
//                    new Movie("Modern Times", "drama"),
//                    new Movie("Giant", "drama"),
//                    new Movie("Platoon", "drama"),
//                    new Movie("Fargo", "drama"),
//                    new Movie("Duck Soup", "comedy"),
//                    new Movie("Mutiny On The Bounty", "drama"),
//                    new Movie("Frankenstein", "horror"),
//                    new Movie("Easy Rider", "drama"),
//                    new Movie("Patton", "drama"),
//                    new Movie("The Jazz Singer", "drama"),
//                    new Movie("My Fair Lady", "musical"),
//                    new Movie("A Place In The Sun", "drama"),
//                    new Movie("The Apartment", "drama"),
//                    new Movie("Goodfellas", "drama"),
//                    new Movie("Pulp Fiction", "drama"),
//                    new Movie("The Searchers", "drama"),
//                    new Movie("Bringing Up Baby", "drama"),
//                    new Movie("Unforgiven", "drama"),
//                    new Movie("Guess Who's Coming To Dinner", "drama"),
                    new Book("Yankee Doodle Dandy",5, "musical")
            };
        }
}
